# Assignment: Data Wrangling
### `! git clone https://github.com/ds3001f25/wrangling_assignment.git`
### Do Q1 and Q2
### Reading material: `tidy_data.pdf`

**Q1.** This question provides some practice cleaning variables which have common problems.
1. Numeric variable: For `./data/airbnb_hw.csv`, clean the `Price` variable as well as you can, and explain the choices you make. How many missing values do you end up with? (Hint: What happens to the formatting when a price goes over 999 dollars, say from 675 to 1,112?)
2. Categorical variable: For the Minnesota police use of for data, `./data/mn_police_use_of_force.csv`, clean the `subject_injury` variable, handling the NA's; this gives a value `Yes` when a person was injured by police, and `No` when no injury occurred. What proportion of the values are missing? Is this a concern? Cross-tabulate your cleaned `subject_injury` variable with the `force_type` variable. Are there any patterns regarding when the data are missing? 
3. Dummy variable: For the pretrial data covered in the lecture `./data/justice_data.parquet`, clean the `WhetherDefendantWasReleasedPretrial` variable as well as you can, and, in particular, replace missing values with `np.nan`.
4. Missing values, not at random: For the pretrial data covered in the lecture, clean the `ImposedSentenceAllChargeInContactEvent` variable as well as you can, and explain the choices you make. (Hint: Look at the `SentenceTypeAllChargesAtConvictionInContactEvent` variable.)

In [25]:
import pandas as pd
import numpy as np
file_path = "./data/airbnb_hw.csv"
airbnb_df = pd.read_csv(file_path)

airbnb_df.head()

Host Id Host Since                                Name Neighbourhood   \
0   5162530        NaN     1 Bedroom in Prime Williamsburg       Brooklyn   
1  33134899        NaN     Sunny, Private room in Bushwick       Brooklyn   
2  39608626        NaN                Sunny Room in Harlem      Manhattan   
3       500  6/26/2008  Gorgeous 1 BR with Private Balcony      Manhattan   
4       500  6/26/2008            Trendy Times Square Loft      Manhattan   

  Property Type  Review Scores Rating (bin)        Room Type  Zipcode  Beds  \
0     Apartment                         NaN  Entire home/apt  11249.0   1.0   
1     Apartment                         NaN     Private room  11206.0   1.0   
2     Apartment                         NaN     Private room  10032.0   1.0   
3     Apartment                         NaN  Entire home/apt  10024.0   3.0   
4     Apartment                        95.0     Private room  10036.0   3.0   

   Number of Records  Number Of Reviews Price  Review Scores Rating  
0                  1                  0   145                   NaN  
1                  1                  1    37                   NaN  
2                  1                  1    28                   NaN  
3                  1                  0   199                   NaN  
4                  1                 39   549                  96.0

In [26]:
airbnb_df['Price'] = pd.to_numeric(airbnb_df['Price'], downcast='integer', errors='coerce')
# have to cast this from object to float otherwise describe doesn't show proper stats
airbnb_df['Price'].describe()

count    30297.000000
mean       153.357032
std        108.895698
min         10.000000
25%         80.000000
50%        125.000000
75%        192.000000
max        999.000000
Name: Price, dtype: float64

In [27]:
airbnb_df['Price'].isnull().sum()
# 181 null vals

np.int64(181)

In [33]:
airbnb_df_cleaned = airbnb_df.dropna(subset=['Price'])
print("\n airbnb df after dropping rows with nan in 'Price':")
print(airbnb_df_cleaned)


 airbnb df after dropping rows with nan in 'Price':
        Host Id Host Since                                Name Neighbourhood   \
0       5162530        NaN     1 Bedroom in Prime Williamsburg       Brooklyn   
1      33134899        NaN     Sunny, Private room in Bushwick       Brooklyn   
2      39608626        NaN                Sunny Room in Harlem      Manhattan   
3           500  6/26/2008  Gorgeous 1 BR with Private Balcony      Manhattan   
4           500  6/26/2008            Trendy Times Square Loft      Manhattan   
...         ...        ...                                 ...            ...   
30473  43022976  8/31/2015   10 Mins to Time Square/two floors         Queens   
30474  42993382  8/31/2015       1BR ocean view & F,Q train st       Brooklyn   
30475  43033067  8/31/2015                Amazing Private Room       Brooklyn   
30476  43000991  8/31/2015   Charming private female room: UWS      Manhattan   
30477  42999189  8/31/2015    Huge Beautiful Bedroom - A

In [34]:
airbnb_df_cleaned.sort_values(by='Price', ascending=False)

Host Id  Host Since                                 Name  \
17664  11260309   1/13/2014               Huge Union Square Loft   
26751  30247261   3/30/2015  NEW 2850 SQ FT SOHO/LittleItaly GEM   
14884   8107868   8/12/2013    Huge Remodeled Home in Prime Area   
17430  10963050    1/2/2014         3BR Luxury Apartment in SoHo   
2955     687750   6/10/2011  Super Big Sunny room. Great view!!!   
...         ...         ...                                  ...   
25139  25038105  12/20/2014  Cool Harlem Room available / shared   
9793    3991870  10/27/2012   1 Couch 8 min from Manhattan J\M\Z   
30087  41211757   8/11/2015         Private Room in Brooklyn, NY   
19275  14381346   4/16/2014                           Small sofa   
3120     751530   6/27/2011      Room in three-Bedroom Apartment   

      Neighbourhood  Property Type  Review Scores Rating (bin)  \
17664      Manhattan     Apartment                         NaN   
26751      Manhattan     Apartment                         NaN   
14884      Manhattan     Apartment                         NaN   
17430      Manhattan     Apartment                         NaN   
2955       Manhattan     Apartment                        85.0   
...              ...           ...                         ...   
25139      Manhattan         House                         NaN   
9793        Brooklyn     Apartment                        80.0   
30087       Brooklyn     Apartment                         NaN   
19275          Bronx         House                       100.0   
3120        Brooklyn     Apartment                         NaN   

             Room Type  Zipcode  Beds  Number of Records  Number Of Reviews  \
17664  Entire home/apt  10003.0   2.0                  1                  0   
26751  Entire home/apt  10013.0   4.0                  1                  0   
14884  Entire home/apt  10014.0   3.0                  1                  0   
17430  Entire home/apt  10012.0   3.0                  1                  0   
2955      Private room  10044.0   2.0                  1                  9   
...                ...      ...   ...                ...                ...   
25139      Shared room  10027.0   1.0                  1                  0   
9793       Shared room  11206.0   1.0                  1                 17   
30087     Private room  11219.0   1.0                  1                  0   
19275      Shared room  10462.0   1.0                  1                  2   
3120   Entire home/apt      NaN   1.0                  1                  0   

       Price  Review Scores Rating  
17664  999.0                   NaN  
26751  999.0                   NaN  
14884  999.0                   NaN  
17430  999.0                   NaN  
2955   999.0                  88.0  
...      ...                   ...  
25139   20.0                   NaN  
9793    20.0                  81.0  
30087   10.0                   NaN  
19275   10.0                 100.0  
3120    10.0                   NaN  

[30297 rows x 13 columns]

### 1.1: 
I cleaned the data by converting the entire Price column to numeric, so now it is a float instead of an object which allows us to use pd.describe to find the max. We can also now check for the number of null values, otherwise known as NaN, and we have 181 null values in Price so I chose to drop those rows from the dataframe. Next, we realized the max is 999 even though the csv has values larger than 999 in the csv which means the formatting chose to convert it to 999 here. </br>
^^ why

**Q2.** Go to https://sharkattackfile.net/ and download their dataset on shark attacks (Hint: `GSAF5.xls`).

1. Open the shark attack file using Pandas. It is probably not a csv file, so `read_csv` won't work.
2. Drop any columns that do not contain data.
3. Clean the year variable. Describe the range of values you see. Filter the rows to focus on attacks since 1940. Are attacks increasing, decreasing, or remaining constant over time?
4. Clean the Age variable and make a histogram of the ages of the victims.
5. What proportion of victims are male?
6. Clean the `Type` variable so it only takes three values: Provoked and Unprovoked and Unknown. What proportion of attacks are unprovoked?
7. Clean the `Fatal Y/N` variable so it only takes three values: Y, N, and Unknown.
8. Are sharks more likely to launch unprovoked attacks on men or women? Is the attack more or less likely to be fatal when the attack is provoked or unprovoked? Is it more or less likely to be fatal when the victim is male or female? How do you feel about sharks?
9. What proportion of attacks appear to be by white sharks? (Hint: `str.split()` makes a vector of text values into a list of lists, split by spaces.)